[package]
name = "vc"
version = "0.1.0"


[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.38"
difference = "2.0.0"
serde = "1.0.201"
serde_json="1.0.117"
similar = "2.5.0"

[dependencies.pyo3]
version = "0.15"
features = ["extension-module"]
